apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-storage
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.className }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
