apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    name: {{ .Values.name }}
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
      protocol: TCP
      name: http
  selector:
    name: {{ .Values.name }}
